const products=[
{id:1,name:'Relaxed Linen Shirt',category:'apparel',price:2450,image:'https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=800&q=82',tag:'Best seller'},
{id:2,name:'Structured Wool Coat',category:'apparel',price:6850,image:'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=800&q=82',tag:'New'},
{id:3,name:'Studio Knit',category:'apparel',price:3200,image:'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=82',tag:''},
{id:4,name:'Everyday Tote',category:'bags',price:2950,image:'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=800&q=82',tag:'New'},
{id:5,name:'Leather Crossbody',category:'bags',price:4100,image:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=82',tag:''},
{id:6,name:'Runner 01',category:'footwear',price:5600,image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=82',tag:'Popular'},
{id:7,name:'Minimal Sneaker',category:'footwear',price:4900,image:'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=82',tag:''},
{id:8,name:'Soft Leather Belt',category:'accessories',price:1750,image:'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=800&q=82',tag:''},
{id:9,name:'Classic Watch',category:'accessories',price:4450,image:'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=82',tag:'New'},
{id:10,name:'Ribbed Cap',category:'accessories',price:1250,image:'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=800&q=82',tag:''},
{id:11,name:'Canvas Overshirt',category:'apparel',price:3650,image:'https://images.unsplash.com/photo-1598032895397-b9472444bf93?auto=format&fit=crop&w=800&q=82',tag:''},
{id:12,name:'City Backpack',category:'bags',price:5200,image:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=82',tag:'Popular'}
];
const money=n=>'৳'+n.toLocaleString('en-BD');
let state={category:'all',sort:'featured',cart:JSON.parse(localStorage.getItem('nova-cart')||'[]')};
const $=s=>document.querySelector(s);
function visible(){let a=products.filter(p=>state.category==='all'||p.category===state.category);if(state.sort==='low')a.sort((x,y)=>x.price-y.price);if(state.sort==='high')a.sort((x,y)=>y.price-x.price);if(state.sort==='name')a.sort((x,y)=>x.name.localeCompare(y.name));return a}
function renderProducts(){const list=visible();$('#resultCount').textContent=`${list.length} pieces`;$('#productGrid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy">${p.tag?`<span class="tag">${p.tag}</span>`:''}<button class="add-btn" data-add="${p.id}">Add to bag&nbsp;&nbsp; +</button></div><div class="product-info"><h3>${p.name}</h3><div class="product-meta"><span>${p.category}</span><strong>${money(p.price)}</strong></div></div></article>`).join('')}
function save(){localStorage.setItem('nova-cart',JSON.stringify(state.cart));renderCart()}
function renderCart(){const count=state.cart.reduce((s,x)=>s+x.qty,0);$('#cartCount').textContent=count;const total=state.cart.reduce((s,x)=>s+x.price*x.qty,0);$('#cartTotal').textContent=money(total);$('#cartItems').innerHTML=state.cart.length?state.cart.map(x=>`<div class="cart-row"><img src="${x.image}" alt="${x.name}"><div><h3>${x.name}</h3><p>${money(x.price)}</p><div class="qty"><button data-dec="${x.id}" aria-label="Decrease quantity">−</button><span>${x.qty}</span><button data-inc="${x.id}" aria-label="Increase quantity">+</button></div></div><button class="remove" data-remove="${x.id}">Remove</button></div>`).join(''):`<div class="empty"><p>Your bag is empty.</p><a href="#shop" class="primary-btn" id="emptyShop">Continue shopping <span>→</span></a></div>`}
function openCart(){closeSearch();$('#cartDrawer').classList.add('open');$('#overlay').classList.add('show');$('#cartDrawer').setAttribute('aria-hidden','false');document.body.classList.add('lock')}
function closeCart(){$('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('show');$('#cartDrawer').setAttribute('aria-hidden','true');document.body.classList.remove('lock')}
function openSearch(){closeCart();$('#searchPanel').classList.add('open');$('#searchPanel').setAttribute('aria-hidden','false');$('#searchInput').focus();document.body.classList.add('lock');search()}
function closeSearch(){$('#searchPanel').classList.remove('open');$('#searchPanel').setAttribute('aria-hidden','true');document.body.classList.remove('lock')}
function search(){const q=$('#searchInput').value.trim().toLowerCase();const found=products.filter(p=>p.name.toLowerCase().includes(q)||p.category.includes(q)).slice(0,7);$('#searchResults').innerHTML=q?found.map(p=>`<div class="search-result"><span>${p.name}</span><strong>${money(p.price)}</strong></div>`).join(''):'<p class="muted">Type to search products, categories or essentials.</p>'}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>e.classList.remove('show'),1800)}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){const p=products.find(x=>x.id===+add.dataset.add),item=state.cart.find(x=>x.id===p.id);if(item)item.qty++;else state.cart.push({...p,qty:1});save();toast(`${p.name} added to your bag`);return}const inc=e.target.closest('[data-inc]');if(inc){state.cart.find(x=>x.id===+inc.dataset.inc).qty++;save();return}const dec=e.target.closest('[data-dec]');if(dec){const item=state.cart.find(x=>x.id===+dec.dataset.dec);item.qty--;if(item.qty<=0)state.cart=state.cart.filter(x=>x.id!==item.id);save();return}const rem=e.target.closest('[data-remove]');if(rem){state.cart=state.cart.filter(x=>x.id!==+rem.dataset.remove);save();return}if(e.target.closest('#emptyShop'))closeCart()});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.category=b.dataset.category;renderProducts()}));
$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderProducts()});$('#cartBtn').addEventListener('click',openCart);$('#cartClose').addEventListener('click',closeCart);$('#overlay').addEventListener('click',closeCart);$('#searchBtn').addEventListener('click',openSearch);$('#searchClose').addEventListener('click',closeSearch);$('#searchInput').addEventListener('input',search);$('#checkoutBtn').addEventListener('click',()=>{if(!state.cart.length){toast('Your bag is empty');return}toast('Checkout is ready for payment integration')});$('#menuBtn').addEventListener('click',()=>{$('.main-nav').classList.toggle('mobile-open')});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();closeSearch()}});renderProducts();renderCart();