const products=[
{id:1,name:'Essential Overshirt',category:'apparel',price:3200,image:'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=900&q=80',desc:'A relaxed overshirt cut from a soft everyday fabric.'},
{id:2,name:'Studio Tee',category:'apparel',price:1450,image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',desc:'A clean heavyweight tee for everyday layering.'},
{id:3,name:'Daily Tote',category:'bags',price:2800,image:'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=80',desc:'A structured carry-all with room for the essentials.'},
{id:4,name:'Minimal Sneaker',category:'footwear',price:5600,image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',desc:'A versatile low-profile sneaker with a clean finish.'},
{id:5,name:'Canvas Cap',category:'accessories',price:1100,image:'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=80',desc:'A simple six-panel cap with an adjustable fit.'},
{id:6,name:'Utility Jacket',category:'apparel',price:4900,image:'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80',desc:'A practical layer with a modern silhouette.'},
{id:7,name:'Leather Crossbody',category:'bags',price:6200,image:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',desc:'Compact leather carry with adjustable strap.'},
{id:8,name:'Classic Runner',category:'footwear',price:6100,image:'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=80',desc:'Comfort-focused everyday runners.'},
{id:9,name:'Knit Polo',category:'apparel',price:2600,image:'https://images.unsplash.com/photo-1625910513413-5fc45f1a9b1f?auto=format&fit=crop&w=900&q=80',desc:'Soft knit polo with a refined collar.'},
{id:10,name:'Travel Wallet',category:'accessories',price:1750,image:'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=80',desc:'Slim wallet for cards, notes and travel essentials.'},
{id:11,name:'Everyday Hoodie',category:'apparel',price:3300,image:'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80',desc:'A soft relaxed hoodie built for everyday comfort.'},
{id:12,name:'Weekender Bag',category:'bags',price:6800,image:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',desc:'A spacious weekend carry with durable construction.'}
];
const API_URL=window.ORDER_API_URL||'';let category='all',cart=JSON.parse(localStorage.getItem('nova-cart')||'[]');
const money=n=>`৳${n.toLocaleString('en-BD')}`;const getProduct=id=>products.find(p=>p.id===Number(id));
function renderProducts(){let list=products.filter(p=>category==='all'||p.category===category);const sort=document.getElementById('sortSelect').value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));document.getElementById('resultCount').textContent=`${list.length} pieces`;document.getElementById('productGrid').innerHTML=list.map(p=>`<article class="product-card"><button class="product-image" data-product="${p.id}" aria-label="View ${p.name}"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="tag">${p.category}</span></button><div class="product-info"><h3>${p.name}</h3><div class="product-meta"><span>${money(p.price)}</span><button class="add-btn-static" data-add="${p.id}">Add to bag</button></div></div></article>`).join('')}
function save(){localStorage.setItem('nova-cart',JSON.stringify(cart));renderCart()};function add(id){const x=cart.find(i=>i.id===id);x?x.qty++:cart.push({id,qty:1});save();toast('Added to your bag')};function change(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<1)cart=cart.filter(i=>i.id!==id);save()};
function renderCart(){const count=cart.reduce((s,i)=>s+i.qty,0),total=cart.reduce((s,i)=>s+getProduct(i.id).price*i.qty,0);document.getElementById('cartCount').textContent=count;document.getElementById('cartTotal').textContent=money(total);document.getElementById('cartItems').innerHTML=cart.length?cart.map(i=>{const p=getProduct(i.id);return `<div class="cart-row"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><p>${money(p.price)}</p><div class="qty"><button data-qty="${p.id}" data-dir="-1">−</button><b>${i.qty}</b><button data-qty="${p.id}" data-dir="1">+</button></div></div><button class="remove" data-remove="${p.id}">Remove</button></div>`}).join(''):'<p class="empty">Your bag is empty.</p>'}
function openModal(id){document.getElementById(id).classList.add('open');document.body.classList.add('lock')};function closeModal(id){document.getElementById(id).classList.remove('open');if(!document.querySelector('.modal.open'))document.body.classList.remove('lock')};function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function showProduct(id){const p=getProduct(id);document.getElementById('productDetail').innerHTML=`<div class="detail-grid"><img src="${p.image}" alt="${p.name}"><div><p class="eyebrow">${p.category}</p><h2>${p.name}</h2><p>${p.desc}</p><strong class="detail-price">${money(p.price)}</strong><button class="primary-btn" data-add="${p.id}">Add to bag <span>→</span></button></div></div>`;openModal('productModal')}
function checkout(){if(!cart.length)return toast('Your bag is empty');const total=cart.reduce((s,i)=>s+getProduct(i.id).price*i.qty,0);document.getElementById('checkoutSummary').innerHTML=`<strong>Order summary</strong><span>${cart.reduce((s,i)=>s+i.qty,0)} item(s) · ${money(total)}</span>`;openModal('checkoutModal')}
document.addEventListener('click',e=>{const addBtn=e.target.closest('[data-add]');if(addBtn){add(Number(addBtn.dataset.add));if(addBtn.closest('#productDetail'))closeModal('productModal');return}const prod=e.target.closest('[data-product]');if(prod){showProduct(prod.dataset.product);return}const q=e.target.closest('[data-qty]');if(q){change(Number(q.dataset.qty),Number(q.dataset.dir));return}const rem=e.target.closest('[data-remove]');if(rem){cart=cart.filter(i=>i.id!==Number(rem.dataset.remove));save();return}const close=e.target.closest('[data-close]');if(close)closeModal(close.dataset.close)});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');category=b.dataset.category;renderProducts()}));document.getElementById('sortSelect').addEventListener('change',renderProducts);document.getElementById('cartBtn').onclick=()=>openModal('cartDrawer');document.getElementById('cartClose').onclick=()=>closeModal('cartDrawer');document.getElementById('checkoutBtn').onclick=()=>{closeModal('cartDrawer');checkout()};document.getElementById('searchBtn').onclick=()=>openModal('searchPanel');document.getElementById('searchClose').onclick=()=>closeModal('searchPanel');document.getElementById('menuBtn').onclick=()=>document.querySelector('.main-nav').classList.toggle('open');document.getElementById('overlay').onclick=()=>document.body.classList.remove('lock');
const searchInput=document.getElementById('searchInput');searchInput.addEventListener('input',()=>{const q=searchInput.value.toLowerCase().trim();document.getElementById('searchResults').innerHTML=products.filter(p=>p.name.toLowerCase().includes(q)||p.category.includes(q)).slice(0,8).map(p=>`<button class="search-result" data-product="${p.id}"><span>${p.name}</span><b>${money(p.price)}</b></button>`).join('')});
document.getElementById('checkoutForm').addEventListener('submit',async e=>{e.preventDefault();if(!cart.length)return toast('Your bag is empty');const form=new FormData(e.target);const order={customer:{name:String(form.get('name')).trim(),phone:String(form.get('phone')).trim(),email:String(form.get('email')).trim(),address:String(form.get('address')).trim(),city:String(form.get('city')).trim(),postal:String(form.get('postal')).trim()},payment:String(form.get('payment')),items:cart.map(i=>{const p=getProduct(i.id);return{id:p.id,name:p.name,qty:i.qty,price:p.price}}),total:cart.reduce((s,i)=>s+getProduct(i.id).price*i.qty,0),createdAt:new Date().toISOString()};if(!order.customer.name||!order.customer.phone||!order.customer.email||!order.customer.address)return toast('Please complete all required fields');const btn=e.target.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Placing order…';try{if(API_URL){const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(order)});if(!r.ok)throw new Error('Order API failed')}else{console.warn('ORDER_API_URL is not configured');}localStorage.removeItem('nova-cart');cart=[];renderCart();closeModal('checkoutModal');document.getElementById('successText').textContent=`Order total ${money(order.total)}. We will contact you at ${order.customer.phone} to confirm delivery.`;openModal('successModal');e.target.reset()}catch(err){toast('Could not place the order. Please try again.')}finally{btn.disabled=false;btn.innerHTML='Place order <span>→</span>'}});
renderProducts();renderCart();